### ISSUE TITLE
NoMethodError headers for Sprockets::StaticAsset

### ISSUE THREAD

**Issue by johncant** [jistr/mobvious#4]
Hi,

I'm getting "undefined method "headers" for Sprockets::StaticAsset:0x........" emanating from lib/mobvious/strategies/cookie.rb

It's fixed in my branch by this commit: https://github.com/johncant/mobvious/commit/40ba69f5a997aa15afa3929905aff477d00b91ba

**Comment by jistr** [comment]
Thanks for the solution, picked into master :)
