### ISSUE TITLE
Routing error uninitialized constant when following setup

### ISSUE THREAD

**Issue by maxxiimo** [jistr/mobvious#5]
I am trying to set up Mobvious in a new Rails 3.2.8 app (Ruby 1.9.3p194), and inexplicably keep getting:

```
Routing Error

uninitialized constant ApplicationHelper::Mobvious
```

Here is the Rails project I'm trying to implement Mobvious into:
- https://github.com/maxxiimo/viewthought

The steps I follow:

**Step 1:** Add the following gems to your Gemfile and then bundle install:

```
gem 'mobvious'
gem 'mobvious-rails'
```

**Step 2:** Add the following into application.rb:

```
# Tell your app to use Mobvious::Manager as Rack middleware.
config.middleware.use Mobvious::Manager
```

**Step 3:** Add the following includes into application_controller.rb and application_helper.rb:

```
include Mobvious::Rails::Controller

include Mobvious::Rails::Helper
```

**Step 4:** Create a initializer file (config/initializers/mobvious.rb) and configure it as follows:

```
Mobvious.configure do |config|
  config.strategies = [ Mobvious::Strategies::MobileESP.new(:mobile_desktop) ]
end
```

Am I missing or misinterpreting a step? I'm just not seeing where my error is coming from. Thanks for the help!

I included the debug stuff you recommended in a previous issue in views/home. The first part returns:

```
#<ActionDispatch::MiddlewareStack:0x4108938 @middlewares=[ActionDispatch::Static, Rack::Lock, #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x3dfea98>, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, ActionDispatch::RemoteIp, ActionDispatch::Reloader, ActionDispatch::Callbacks, ActiveRecord::ConnectionAdapters::ConnectionManagement, ActiveRecord::QueryCache, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ParamsParser, ActionDispatch::Head, Rack::ConditionalGet, Rack::ETag, ActionDispatch::BestStandardsSupport]> 
```

Uncommented the second part returns:

```
NameError in Pages#home

Showing C:/Projects/viewthought/app/views/pages/home.html.haml where line #15 raised:

uninitialized constant ActionView::CompiledTemplates::Mobvious
```

**Comment by maxxiimo** [comment]
No problem here. I just needed to restart the application.

**Comment by jistr** [comment]
:))

**Comment by maxxiimo** [comment]
FYI -  I included your gem in a chapter of my book:

https://github.com/maxxiimo/the-front-end-manifesto/blob/master/mobile-foundation.md#advanced-solution

It's a rough draft, but coming along just fine. If you have any critiques I'm open ears, or if you would like to add anything I'd be happy to include it.

My book is a free book.

Cheers!

**Comment by jistr** [comment]
Wow! Thanks for letting me know.

I think responsive web design is going to be preferred over server-based solutions for vast majority of use cases in the future, for two main reasons:
1. Boundaries within device types blend. It used to be PCs and phones, now it's tablets, TVs, e-book readers and more. It's hard to detect them server-side and for some of them, even if you know what device it is, you're still not sure what category should they belong to :) Hence the term "phablets" :)
2. Bandwidth is less of an issue, year by year. It will be best to send the whole thing to the client, then detect client's precise capabilities and render what you want, how you want.

But it's nice to know that Mobvious is still useful :)

I wish you success with the book :)

**Comment by maxxiimo** [comment]
You're welcome and thanks too... your comment above is so insightful. Would you mind if I use that in my book? Here is how it would be included:

https://github.com/maxxiimo/the-front-end-manifesto/blob/master/mobile-foundation.md#plan-of-attack

I'm wondering now if my hybrid approach which I haven't yet written, is sustainable? It uses your gem to distinguish between super small screens and the tablets/desktop category. My thinking is that the difference in screen sizes are so great between both ends of the spectrum that it might be a good idea to design for both, then within one or both, if required, use RWD.

**Comment by jistr** [comment]
> You're welcome and thanks too... your comment above is so insightful. Would you mind if I use that in my book? Here is how it would be included:
> 
> https://github.com/maxxiimo/the-front-end-manifesto/blob/master/mobile-foundation.md#plan-of-attack

Sure, use my comment if you want :)

> I'm wondering now if my hybrid approach which I haven't yet written, is sustainable? It uses your gem to distinguish between super small screens and the tablets/desktop category. My thinking is that the difference in screen sizes are so great between both ends of the spectrum that it might be a good idea to design for both, then within one or both, if required, use RWD.

Yes I think this approach might be better for some cases than just one RWD version. Two versions, one small and one big, both aware of touch displays, might be good. But the thing that I question the most is whether user-agent server-side detection should be the way of detecting which device should use which version. User agent detection is not precise and it's not future proof (you must update it when new devices enter the market). Also, it's a wild heuristic, so it is prone to giving bad results sometimes (see issue #3). I think it might be better to detect precise device capabilities with something like Enquire.js [1] and redirect the browser when you detect that big device attempted to use interface for small displays or vice versa. I never tried this approach, though.

Makes me realize I'm generally getting out of date on front-end stuff :) Nowadays I'm designing and implementing REST APIs, so I can't keep up on front-end anymore.

[1] http://wickynilliams.github.com/enquire.js/
