### ISSUE TITLE
Detection of nexus7 browsers

### ISSUE THREAD

**Issue by dimitrismistriotis** [jistr/mobvious#9]
Hi, 

Please inform me to remove/close if this is off-topic.

I use mobvious and for my nexus7 device, both chrome and firefox set 'device_type' to ':desktop'. Shouldn't it be ':tablet'?

The above is confirmed from the specs (https://github.com/jistr/mobvious/blob/master/spec/mobvious/strategies/mobileesp_spec.rb) , is this intentional?

```
  it "categorizes Android tablet as :desktop" do
    @request.stubs(:user_agent).returns("Mozilla/5.0 (Linux; U; Android 3.0; en-us; Xoom Build/HRI39) AppleWebKit/534.13 (KHTML, like Gecko) Version/4.0 Safari/534.13")
    @strategy.get_device_type(@request).must_equal :desktop
  end
```

**Comment by jistr** [comment]
Hi Dimitris,

yes it should be :tablet. The current detection mechanism is probably short here. I don't have enough bandwidth to fix that myself though, as I don't use Mobvious for any projects for a while now.

**Comment by dimitrismistriotis** [comment]
Hi,

I spend some time on this and two comments:
1. Gemfile changes to make it work (on my machine):

https://github.com/dimitrismistriotis/mobvious/commit/4b6deb0aac8d4c88c5efcd76aa35d5d997edf3b5
1. After this I read the source code in order to provide amends. For the default strategy, [mobileesp_converted](https://github.com/jistr/mobileesp_converted) is used, which uses :mobile_desktop as default strategy. Because it is assumed, by reading the "README" that tablet is detected, I suggest to either update the readme

https://github.com/dimitrismistriotis/mobvious/commit/866ebc08ba566c22efc9051fefa52451de39d50d

or the default.

I used an initializer containing this on my production system and android tablet was detected...

Hope I helped, please tell me if I should send a pull request.

D.

**Comment by jistr** [comment]
Hi,

I now recall that the default of mobile-desktop is on purpose, since people don't often make specialized sites for tablets.

Please send a pull request with the gemfile changes. Thanks!

Jirka

**Comment by dimitrismistriotis** [comment]
https://github.com/jistr/mobvious/pull/10 For the pull request. 

You are basically right, at some point I will do the same thing, one strategy for mobile and one for "other" for my application. When this happens, I will have a `device_type != :mobile` check.
